### ISSUE TITLE
Can't enable keyboardNavigation

### ISSUE THREAD

**Issue by rusllonrails** [Nerian/bootstrap-datepicker-rails#101]
Hey guys,

I use latest version of gem.

Gemfile:
```
gem 'bootstrap-datepicker-rails', require: 'bootstrap-datepicker-rails',
                                  git: 'git://github.com/Nerian/bootstrap-datepicker-rails.git'
```

JS:
```
$("#from").datepicker
      defaultDate: "+1w"
      format: "dd/mm/yyyy"
      language: "ru"
      changeMonth: true
      keyboardNavigation: true
```

HTML:
```
.input-group.date
   = text_field_tag "search[start_date]", nil, class: 'form-control', id: 'from'
   span.input-group-addon
       i.glyphicon.glyphicon-th
```

All works good! 
On my side keyboardNavigation icon appears, but do nothing when I'm click on it.
I don't think that is gem issue, just wanted to ask if someone had same issue and fixed it?

Thanks :beers:

**Comment by svavantsa** [comment]
ᐧ

On Sun, Mar 29, 2015 at 5:17 AM, Ruslan Khamidullin <
notifications@github.com> wrote:

> keyboardNavigation: true


Looks like your issue is resolved, from what you are saying.

The keyboardNavigation is true by default. If you set it to false, then the
keyboard doesn't work on the calendar widget. Hope that helps.


Thank You,

Surya Avantsa

<http://vame.me/suryaavantsa>
